const { test, expect } = require('@playwright/test');
const AxeBuilder = require('@axe-core/playwright').default;
const fs = require('fs');
const path = require('path');
const ROOT=path.resolve(__dirname,'..'),BASE=process.env.BASE_URL||'http://127.0.0.1:4173';
const ALL_PAGES=fs.readdirSync(ROOT).filter(f=>f.endsWith('.html')).sort();
const KEY_PAGES=['index.html','products.html','services.html','research.html','about.html','news.html','contact.html','careers.html'];
const VIEWPORTS=[['compact-phone',360,800],['phone',390,844],['large-phone',430,932],['tablet-portrait',768,1024],['tablet-large',820,1180],['laptop',1280,800],['desktop',1440,900],['wide',1920,1080]];
function rgb(v){const m=v&&v.match(/rgba?\((\d+)[, ]+\s*(\d+)[, ]+\s*(\d+)(?:[, /]+\s*([\d.]+))?\)/i);return m?{r:+m[1],g:+m[2],b:+m[3],a:m[4]===undefined?1:+m[4]}:null}
function lum({r,g,b}){const f=c=>{c/=255;return c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4)};return .2126*f(r)+.7152*f(g)+.0722*f(b)}
async function noDark(page,label){const rows=await page.locator('body *').evaluateAll(ns=>ns.map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return{tag:e.tagName,cls:String(e.className||''),bg:s.backgroundColor,d:s.display,v:s.visibility,w:r.width,h:r.height}}).filter(x=>x.d!=='none'&&x.v!=='hidden'&&x.w>20&&x.h>20));const bad=rows.filter(x=>{const c=rgb(x.bg);return c&&c.a>.85&&lum(c)<.08});expect(bad.slice(0,12),`${label}: dark background surfaces`).toEqual([])}
async function noOverflow(page,label){const d=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,bw:document.body.scrollWidth}));expect(d.sw,`${label}: document overflow`).toBeLessThanOrEqual(d.cw+2);expect(d.bw,`${label}: body overflow`).toBeLessThanOrEqual(d.cw+2)}
for(const [name,width,height] of VIEWPORTS)test.describe(`viewport ${name}`,()=>{test.use({viewport:{width,height}});for(const file of KEY_PAGES)test(`${file} renders cleanly`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(`${BASE}/${file}`,{waitUntil:'networkidle'});await expect(page.locator('h1')).toHaveCount(1);await noOverflow(page,`${name}/${file}`);await noDark(page,`${name}/${file}`);expect(errors.filter(x=>!x.includes('favicon'))).toEqual([])})});
test.describe('all-page structural smoke',()=>{for(const viewport of [{width:390,height:844},{width:1440,height:900}])for(const file of ALL_PAGES)test(`${file} @ ${viewport.width}`,async({page})=>{await page.setViewportSize(viewport);const res=await page.goto(`${BASE}/${file}`,{waitUntil:'domcontentloaded'});expect(res&&res.ok(),`${file}: HTTP`).toBeTruthy();await noOverflow(page,`${file}/${viewport.width}`);const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.offsetParent!==null&&(!i.complete||i.naturalWidth===0)).map(i=>i.getAttribute('src')));expect(broken,`${file}: broken images`).toEqual([])})});
test('mobile navigation opens and closes on navigation',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(`${BASE}/index.html`);const menu=page.locator('.menu-toggle');await expect(menu).toBeVisible();const box=await menu.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44);expect(box.width).toBeGreaterThanOrEqual(44);await menu.click();await expect(page.locator('.head-links')).toHaveClass(/open/);await page.locator('.head-links a[href="products.html"]').click();await expect(page).toHaveURL(/products\.html/)});
test('search opens filters and closes',async({page})=>{await page.setViewportSize({width:1440,height:900});await page.goto(`${BASE}/index.html`);await page.locator('.search-button').click();await expect(page.locator('.search-dialog')).toHaveClass(/open/);await page.locator('#siteSearch').fill('floating point');await expect(page.locator('.search-results')).toContainText('Floating-point IP');await page.locator('.search-close').click();await expect(page.locator('.search-dialog')).not.toHaveClass(/open/)});
test('IP explorer exposes 9 arithmetic and 4 interface blocks',async({page})=>{await page.goto(`${BASE}/products.html`,{waitUntil:'networkidle'});await expect(page.locator('.ip-explorer-tools')).toBeVisible();await page.locator('.ip-filter[data-filter="interface"]').click();expect(await page.locator('.listing-row[data-ip-category="interface"]').evaluateAll(rs=>rs.filter(r=>getComputedStyle(r).display!=='none').length)).toBe(4);await page.locator('.ip-filter[data-filter="arithmetic"]').click();expect(await page.locator('.listing-row[data-ip-category="arithmetic"]').evaluateAll(rs=>rs.filter(r=>getComputedStyle(r).display!=='none').length)).toBe(9)});
test('contact context prefills from IP and service links',async({page})=>{await page.goto(`${BASE}/contact.html?ip=fp-multiplier`);await expect(page.locator('#projectType')).toHaveValue('IP licensing / evaluation');await expect(page.locator('#service')).toHaveValue('Semiconductor IP');await expect(page.locator('.route-context')).toContainText('FP Multiplier');await page.goto(`${BASE}/contact.html?service=verification`);await expect(page.locator('#projectType')).toHaveValue('Verification / coverage closure');await expect(page.locator('#service')).toHaveValue('UVM verification')});
test('contact validation rejects free email and short context',async({page})=>{await page.goto(`${BASE}/contact.html`);await page.locator('#technicalEnquiry').evaluate(f=>f.noValidate=true);await page.locator('#name').fill('Test Engineer');await page.locator('#email').fill('test@gmail.com');await page.locator('#company').fill('Example Labs');await page.locator('#projectType').selectOption({label:'RTL design'});await page.locator('#description').fill('This is deliberately longer than forty characters for the email validation test.');await page.locator('input[name="consent"]').check();await page.locator('button[type="submit"]').click();await expect(page.locator('.form-error')).toContainText('work or institutional email');await page.locator('#email').fill('engineer@example.com');await page.locator('#description').fill('too short');await page.locator('button[type="submit"]').click();await expect(page.locator('.form-error')).toContainText('technical context')});
test('successful enquiry UI redirects with mocked backend and writes no real lead',async({page})=>{await page.route('**/functions/v1/website-enquiry',r=>r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,enquiry_id:'ci-test'})}));await page.goto(`${BASE}/contact.html?service=rtl&utm_source=ci`);await page.locator('#name').fill('CI Engineer');await page.locator('#email').fill('ci@example.com');await page.locator('#company').fill('CI Semiconductor');await page.locator('#projectType').selectOption({label:'RTL design'});await page.locator('#description').fill('We need synthesizable RTL for a bounded digital block with verification collateral and FPGA integration evidence.');await page.locator('input[name="consent"]').check();await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/enquiry-received\.html\?id=ci-test/)});
test('important mobile controls meet 44px enhanced target guidance',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(`${BASE}/contact.html`);const bad=await page.locator('button:visible,input:not([type="checkbox"]):visible,select:visible,textarea:visible,.action:visible,.mobile-dock a:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{name:e.getAttribute('aria-label')||e.textContent.trim().slice(0,35)||e.getAttribute('name'),w:r.width,h:r.height}}).filter(x=>x.w<44||x.h<44));expect(bad).toEqual([])});
for(const file of ['index.html','products.html','services.html','contact.html'])test(`WCAG serious/critical smoke — ${file}`,async({page})=>{await page.setViewportSize({width:1440,height:900});await page.goto(`${BASE}/${file}`,{waitUntil:'networkidle'});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();const severe=result.violations.filter(v=>['serious','critical'].includes(v.impact));expect(severe.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.slice(0,4).map(n=>n.target)}))).toEqual([])});
test('capture responsive review artifacts',async({page})=>{fs.mkdirSync(path.join(ROOT,'test-results','screens'),{recursive:true});for(const vp of [{name:'phone',width:390,height:844},{name:'tablet',width:768,height:1024},{name:'desktop',width:1440,height:900},{name:'wide',width:1920,height:1080}]){await page.setViewportSize({width:vp.width,height:vp.height});for(const file of ['index.html','products.html','services.html','contact.html']){await page.goto(`${BASE}/${file}`,{waitUntil:'networkidle'});await page.screenshot({path:path.join(ROOT,'test-results','screens',`${file.replace('.html','')}-${vp.name}.png`),fullPage:true})}}});
